.PHONY: run1 run2 run3

# Really useful flag: 

run1:
	@gcc 01.c -o 01.exe -lm -Wpedantic -Wall -Wextra -fanalyzer
	@./01.exe

run2:
	@gcc 02.c -o 02.exe -lm -Wpedantic -Wall -Wextra -fanalyzer
	@./02.exe
