.PHONY: run1 run2 run3

# -

run1:
	@gcc 01.c -o 01.exe -lm -Wpedantic -Wall -Wextra
	@./01.exe

run2:
	@gcc 02.c -o 02.exe -lm -Wpedantic -Wall -Wextra
	@./02.exe

run3:
	@gcc 03.c -o 03.exe -lm -Wpedantic -Wall -Wextra
	@./03.exe